version: "3.9"

services:
  nextcloud:
    image: 'nextcloud/all-in-one:latest'
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './config:/mnt/docker-aio-config'
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.${BASE_DOMAIN:-ozeliurs.com}`)'
      - 'traefik.http.routers.nextcloud.entrypoints=websecure'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.tls.certresolver=cloudflare'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'

networks:
  traefik:
    external: true